/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prediccion_y_analisis_de_riesgos;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author mariopl
 */
public class Registrar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registrar.class.getName());

    /**
     * Creates new form Registrar
     */
    public Registrar() {
        initComponents();
    }
    private String obtenerOCrearIdBien(String descripcionBien, String tipoBien, String idCliente) throws SQLException {
    conexion con = new conexion();
    Connection cn = con.getConnection();
    Statement st = cn.createStatement();

    // 1) Buscar si ya existe un bien con esa descripción para ese cliente
    String sqlBusca = "SELECT idBien FROM bienes " +
                      "WHERE descripcion = '" + descripcionBien + "' " +
                      "AND idCliente = '" + idCliente + "'";
    ResultSet rs = st.executeQuery(sqlBusca);
    if (rs.next()) {
        return rs.getString("idBien");
    }

    // 2) No existe: generar nuevo idBien
    String sqlMax = "SELECT MAX(idBien) FROM bienes";
    ResultSet rsMax = st.executeQuery(sqlMax);
    String nuevoId;
    if (rsMax.next() && rsMax.getString(1) != null) {
        String ultimo = rsMax.getString(1);       // ej. "B0000008"
        int num = Integer.parseInt(ultimo.substring(1)); // quita la 'B'
        num++;
        nuevoId = String.format("B%07d", num);    // B + 7 dígitos
    } else {
        nuevoId = "B0000001";
    }

    String sqlInserta = "INSERT INTO bienes (idBien, idCliente, descripcion, valorAsegurado, tipoBien) " +
                        "VALUES ('" + nuevoId + "', '" + idCliente + "', '" + descripcionBien +
                        "', 0, '" + tipoBien + "')";
    st.executeUpdate(sqlInserta);

    return nuevoId;
}

    

// Busca idRiesgo a partir del nombre del riesgo
private String obtenerIdRiesgoPorNombre(String nombreRiesgo) throws SQLException {
    conexion con = new conexion();
    Connection cn = con.getConnection();
    String sql = "SELECT idRiesgo FROM tiposRiesgo WHERE nombreRiesgo = '" + nombreRiesgo + "'";
    Statement st = cn.createStatement();
    ResultSet rs = st.executeQuery(sql);
    return rs.next() ? rs.getString("idRiesgo") : null;
}

// Busca idAseguradora a partir del nombre
private String obtenerIdAseguradoraPorNombre(String nombreAseg) throws SQLException {
    conexion con = new conexion();
    Connection cn = con.getConnection();
    String sql = "SELECT idAseguradora FROM aseguradoras WHERE nombre = '" + nombreAseg + "'";
    Statement st = cn.createStatement();
    ResultSet rs = st.executeQuery(sql);
    return rs.next() ? rs.getString("idAseguradora") : null;
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdSiniestro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbxTipoBien = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbxTipoRiesgo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbxAseguradora = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbxZona = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtBienDescripcion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbxIdCliente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel4.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Favor de llenar los campos para registrar un nuevo siniestro");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel5.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("id Siniestro");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        txtIdSiniestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdSiniestroActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tipo de Bien ");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel6.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        cbxTipoBien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auto", "Casa", "Negocio", "Moto", "Departamento" }));

        jLabel7.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo de riesgo");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel7.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        cbxTipoRiesgo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Incendio", "Robo", "Accidente", "Inundación", "Vandalismo" }));

        jLabel8.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Aseguradora");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel8.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        cbxAseguradora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seguros Norte", "Seguros Sur", "Seguros Este", "Solidez MX", "Mega Seguros" }));

        jLabel9.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha del siniestro");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel9.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        txtFecha.setText("AAAA-MM-DD");

        jLabel10.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Monto del siniestro");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel10.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel11.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Zona");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel11.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        cbxZona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centro", "Norte", "Sur", "Este", "Campo" }));

        jLabel12.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Descripción");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel12.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        btnGuardar.setText("Guardar/Registrar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Bien asegurado");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel13.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        txtBienDescripcion.setText("Descripción");

        jLabel14.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("id Cliente");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel14.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        cbxIdCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C001", "C002", "C003", "C004", "C005" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel5)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdSiniestro)
                            .addComponent(txtFecha)
                            .addComponent(txtMonto)
                            .addComponent(cbxZona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDescripcion)
                            .addComponent(cbxTipoBien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxTipoRiesgo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxAseguradora, 0, 136, Short.MAX_VALUE)
                            .addComponent(txtBienDescripcion)
                            .addComponent(cbxIdCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(btnLimpiar)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegresar)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIdSiniestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtBienDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxTipoBien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxTipoRiesgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbxAseguradora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbxZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbxIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(27, 27, 27)
                .addComponent(btnLimpiar)
                .addGap(2, 2, 2)
                .addComponent(btnRegresar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdSiniestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdSiniestroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdSiniestroActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

    limpiarCampos();


    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        new MenuPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    String idSiniestro = txtIdSiniestro.getText().trim();
    String descBien    = txtBienDescripcion.getText().trim();
    String tipoBien    = cbxTipoBien.getSelectedItem().toString();
    String nombreRiesgo = cbxTipoRiesgo.getSelectedItem().toString();
    String nombreAseg   = cbxAseguradora.getSelectedItem().toString();
    String fecha        = txtFecha.getText().trim();
    String montoTexto   = txtMonto.getText().trim();
    String zona         = cbxZona.getSelectedItem().toString();
    String descripcion  = txtDescripcion.getText().trim();
    String idCliente    = cbxIdCliente.getSelectedItem().toString();

    // Validaciones básicas (igual que antes)
    if (idSiniestro.isEmpty() || descBien.isEmpty() || nombreRiesgo.isEmpty() ||
        nombreAseg.isEmpty() || fecha.isEmpty() || montoTexto.isEmpty() ||
        zona.isEmpty() || descripcion.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Por favor, llene todos los campos antes de guardar.");
        return;
    }

    double monto;
    try {
        monto = Double.parseDouble(montoTexto);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this,
            "El monto del siniestro debe ser numérico.");
        return;
    }

    try {
        // AQUÍ se obtiene idBien y si hay SQLException se va directo al catch de abajo
        String idBien        = obtenerOCrearIdBien(descBien, tipoBien, idCliente);
        String idRiesgo      = obtenerIdRiesgoPorNombre(nombreRiesgo);
        String idAseguradora = obtenerIdAseguradoraPorNombre(nombreAseg);

        if (idRiesgo == null || idAseguradora == null) {
            JOptionPane.showMessageDialog(this,
                "Error: no se encontraron los IDs correspondientes en la base de datos.");
            return;
        }

        conexion con = new conexion();
        Connection cn = con.getConnection();
        Statement st = cn.createStatement();

        String sql = "INSERT INTO `siniestros/eventos` " +
                     "(idSiniestro, idBien, idRiesgo, idAseguradora, fecha, monto, zona, descripcion) " +
                     "VALUES ('" + idSiniestro + "', '" + idBien + "', '" + idRiesgo + "', '" +
                     idAseguradora + "', '" + fecha + "', " + monto + ", '" + zona + "', '" +
                     descripcion + "')";
        int filas = st.executeUpdate(sql);

        if (filas > 0) {
            JOptionPane.showMessageDialog(this,
                "Siniestro registrado correctamente.");
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this,
                "No se pudo registrar el siniestro.");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this,
            "Error al registrar el siniestro: " + ex.getMessage());
    }
    
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registrar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbxAseguradora;
    private javax.swing.JComboBox<String> cbxIdCliente;
    private javax.swing.JComboBox<String> cbxTipoBien;
    private javax.swing.JComboBox<String> cbxTipoRiesgo;
    private javax.swing.JComboBox<String> cbxZona;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtBienDescripcion;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdSiniestro;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        
    txtIdSiniestro.setText("");
    txtBienDescripcion.setText("");
    cbxTipoBien.setSelectedIndex(0);
    cbxTipoRiesgo.setSelectedIndex(0);
    cbxAseguradora.setSelectedIndex(0);
    txtFecha.setText("AAAA-MM-DD");
    txtMonto.setText("");
    cbxZona.setSelectedIndex(0);
    txtDescripcion.setText("");
    cbxIdCliente.setSelectedIndex(0);
}
 // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    
}
