/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prediccion_y_analisis_de_riesgos;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author mariopl
 */
public class RiesgoEsperado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RiesgoEsperado.class.getName());

    /**
     * Creates new form RiesgoEsperado
     */
    public RiesgoEsperado() {
        initComponents();
    }
    private String obtenerIdRiesgoPorNombre(String nombreRiesgo) throws SQLException {
    conexion con = new conexion();
    Connection cn = con.getConnection();
    String sql = "SELECT idRiesgo FROM tiposRiesgo WHERE nombreRiesgo = '" + nombreRiesgo + "'";
    Statement st = cn.createStatement();
    ResultSet rs = st.executeQuery(sql);
    if (rs.next()) {
        return rs.getString("idRiesgo");
    } else {
        return null;
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxTipoRiesgo = new javax.swing.JComboBox<>();
        btnMedir = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Medir el riesgo que más afecta a un tipo de bien");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Riesgo esperado");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel4.setFont(new java.awt.Font("Heiti SC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Medir el riesgo esperado por tipo de riesgo");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel4.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel5.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Por favor, seleccione un tipo de riesgo");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        cbxTipoRiesgo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Incendio", "Robo", "Accidente", "Inundación", "Vandalismo" }));

        btnMedir.setText("Medir");
        btnMedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedirActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegresar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbxTipoRiesgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMedir))
                            .addComponent(jLabel5))
                        .addGap(82, 82, 82)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTipoRiesgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMedir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegresar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        new ReportesRiesgo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnMedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedirActionPerformed
        String nombreRiesgo = cbxTipoRiesgo.getSelectedItem().toString();

    try {
        // 1. Obtener el idRiesgo real desde la tabla tiposRiesgo
        String idRiesgo = obtenerIdRiesgoPorNombre(nombreRiesgo);
        if (idRiesgo == null) {
            JOptionPane.showMessageDialog(this,
                "No se encontró el tipo de riesgo seleccionado en la tabla tiposRiesgo.");
            return;
        }

        conexion con = new conexion();
        Connection cn = con.getConnection();
        Statement st = cn.createStatement();

        // 2. Contar cuántos siniestros corresponden a ese riesgo
        ResultSet rs1 = st.executeQuery(
            "SELECT COUNT(*) FROM `siniestros/eventos` WHERE idRiesgo = '" + idRiesgo + "'");
        rs1.next();
        double nRiesgo = rs1.getInt(1);

        // 3. Contar el total de siniestros de la base
        ResultSet rs2 = st.executeQuery(
            "SELECT COUNT(*) FROM `siniestros/eventos`");
        rs2.next();
        double nTotal = rs2.getInt(1);

        // 4. Calcular la severidad promedio (monto promedio) para ese riesgo
        ResultSet rs3 = st.executeQuery(
            "SELECT AVG(monto) FROM `siniestros/eventos` WHERE idRiesgo = '" + idRiesgo + "'");
        rs3.next();
        double severidadProm = rs3.getDouble(1);

        // Validación por si aún no hay datos suficientes
        if (nTotal == 0 || nRiesgo == 0) {
            JOptionPane.showMessageDialog(this,
                "No hay siniestros suficientes para calcular el riesgo esperado para " + nombreRiesgo + ".");
            return;
        }

        // 5. Frecuencia (probabilidad estimada) = siniestros de ese riesgo / total de siniestros
        double prob = nRiesgo / nTotal;

        // 6. Riesgo esperado = frecuencia × severidad promedio
        double riesgoEsperado = prob * severidadProm;

        // 7. Mostrar resultado al usuario
        JOptionPane.showMessageDialog(this,
            "Para el riesgo \"" + nombreRiesgo + "\" (" + idRiesgo + "):" +
            "\nFrecuencia = " + prob +
            "\nSeveridad promedio = " + severidadProm +
            "\nRiesgo esperado = " + riesgoEsperado);
    } catch (SQLException ex) {
        // En caso de error de conexión o SQL, se informa en un cuadro de diálogo
        JOptionPane.showMessageDialog(this,
            "Error al calcular el riesgo esperado: " + ex.getMessage());
    }                                  

    }//GEN-LAST:event_btnMedirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RiesgoEsperado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMedir;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbxTipoRiesgo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
